### ISSUE TITLE
Subir archivo .PHP para trabajo por medio de issue

### ISSUE THREAD

**Issue by ghost** [MonicaAguilar99/curriculumvitae#1]
Subir archivo con los comandos de add, commit, push.

**Comment by MonicaAguilar99** [comment]
Enviado desde Outlook<http://aka.ms/weboutlook>
________________________________
De: MrHuskyE ***@***.***>
Enviado: martes, 9 de agosto de 2022 20:20
Para: MonicaAguilar99/curriculumvitae ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [MonicaAguilar99/curriculumvitae] Subir archivo .PHP para trabajo por medio de issue (Issue #1)


Subir archivo con los comandos de add, commit, push.
